/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JApplet.java to edit this template
 */

/**
 *
 * @author LENOVO
 */
public class JAppletEj3 extends javax.swing.JApplet {

    /**
     * Initializes the applet JAppletEj3
     */
    @Override
    public void init() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JAppletEj3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JAppletEj3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JAppletEj3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JAppletEj3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the applet */
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        jTextMedidaA = new javax.swing.JTextField();
        jTextMedidaC = new javax.swing.JTextField();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        jLabelResultadoTipoTriangulo = new javax.swing.JLabel();
        javax.swing.JLabel jLabel7 = new javax.swing.JLabel();
        jLabelResultadoAngulosTriangulo = new javax.swing.JLabel();
        javax.swing.JLabel jLabel9 = new javax.swing.JLabel();
        jLabelResultadoAreaTriangulo = new javax.swing.JLabel();
        jButtonCalcuLcularTipoTriangulo = new javax.swing.JButton();
        javax.swing.JLabel jLabel6 = new javax.swing.JLabel();
        jTextMedidaAltura = new javax.swing.JTextField();
        jButtonCalcularAngulos = new javax.swing.JButton();
        jButtonCalcularArea = new javax.swing.JButton();
        jTextMedidaB = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(" Triángulo; equilátero, isósceles o escaleno? Ingresa las medidas:");

        jLabel2.setText("A :");

        jLabel3.setText("B :");

        jLabel4.setText("C :");

        jTextMedidaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextMedidaAActionPerformed(evt);
            }
        });

        jTextMedidaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextMedidaCActionPerformed(evt);
            }
        });

        jLabel5.setText("Tu triángulo es: ");

        jLabel7.setText("Ángulos:");

        jLabel9.setText("Área del triángulo:");

        jButtonCalcuLcularTipoTriangulo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonCalcuLcularTipoTriangulo.setText("Tipo de Triángulo");
        jButtonCalcuLcularTipoTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcuLcularTipoTrianguloActionPerformed(evt);
            }
        });

        jLabel6.setText("Altura:");

        jButtonCalcularAngulos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonCalcularAngulos.setText("Calcular ángulos");
        jButtonCalcularAngulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularAngulosActionPerformed(evt);
            }
        });

        jButtonCalcularArea.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonCalcularArea.setText("Calcular Área");
        jButtonCalcularArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularAreaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonCalcuLcularTipoTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(jButtonCalcularAngulos)
                                .addGap(33, 33, 33)
                                .addComponent(jButtonCalcularArea, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextMedidaC, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                        .addComponent(jTextMedidaAltura)
                                        .addComponent(jTextMedidaA)
                                        .addComponent(jTextMedidaB)))))
                        .addContainerGap(124, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelResultadoTipoTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelResultadoAngulosTriangulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelResultadoAreaTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextMedidaA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextMedidaB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextMedidaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextMedidaAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonCalcuLcularTipoTriangulo, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jButtonCalcularAngulos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCalcularArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelResultadoTipoTriangulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelResultadoAngulosTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelResultadoAreaTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCalcuLcularTipoTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcuLcularTipoTrianguloActionPerformed
         // Obtener las medidas ingresadas por el usuario
    double ladoA = Double.parseDouble(jTextMedidaA.getText());
    double ladoB = Double.parseDouble(jTextMedidaB.getText());
    double ladoC = Double.parseDouble(jTextMedidaC.getText());

    // Verificar si es un triángulo válido
    if (esTrianguloValido(ladoA, ladoB, ladoC)) {
        // Calcular el tipo de triángulo
        String tipoTriangulo = calcularTipoTriangulo(ladoA, ladoB, ladoC);

        // Mostrar el tipo de triángulo en pantalla
        jLabelResultadoTipoTriangulo.setText(tipoTriangulo);
    } else {
        // Si no es un triángulo válido, mostrar un mensaje de error
        jLabelResultadoTipoTriangulo.setText("No es un triángulo válido.");
    }
}

// Método para verificar si es un triángulo válido
private boolean esTrianguloValido(double ladoA, double ladoB, double ladoC) {
    return (ladoA + ladoB > ladoC) && (ladoA + ladoC > ladoB) && (ladoB + ladoC > ladoA);
}

// Método para calcular el tipo de triángulo
private String calcularTipoTriangulo(double ladoA, double ladoB, double ladoC) {
    if (ladoA == ladoB && ladoB == ladoC) {
        return "Equilátero";
    } else if (ladoA == ladoB || ladoA == ladoC || ladoB == ladoC) {
        return "Isósceles";
    } else {
        return "Escaleno";
    }   
    }//GEN-LAST:event_jButtonCalcuLcularTipoTrianguloActionPerformed

    private void jTextMedidaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextMedidaAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextMedidaAActionPerformed

    private void jTextMedidaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextMedidaCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextMedidaCActionPerformed

    private void jButtonCalcularAngulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularAngulosActionPerformed
        // Obtener las medidas ingresadas por el usuario
        double ladoA = Double.parseDouble(jTextMedidaA.getText());
        double ladoB = Double.parseDouble(jTextMedidaB.getText());
        double ladoC = Double.parseDouble(jTextMedidaC.getText());

        // Calcular los ángulos del triángulo
        double anguloA = calcularAngulo(ladoB, ladoC, ladoA);
        double anguloB = calcularAngulo(ladoA, ladoC, ladoB);
        double anguloC = calcularAngulo(ladoA, ladoB, ladoC);

        // Mostrar el resultado en pantalla
        jLabelResultadoAngulosTriangulo.setText("Ángulo A: " + anguloA + " grados, Ángulo B: " + anguloB + " grados, Ángulo C: " + anguloC + " grados");
    }

    private double calcularAngulo(double ladoA, double ladoB, double ladoC) {
        // Calcular el ángulo utilizando el teorema del coseno: a^2 = b^2 + c^2 - 2bc * cos(A)
        double cosA = (ladoB * ladoB + ladoC * ladoC - ladoA * ladoA) / (2 * ladoB * ladoC);
        double angulo = Math.toDegrees(Math.acos(cosA));
        return angulo;
    
        
    }//GEN-LAST:event_jButtonCalcularAngulosActionPerformed

    private void jButtonCalcularAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularAreaActionPerformed
        // Obtener las medidas ingresadas por el usuario
        double ladoA = Double.parseDouble(jTextMedidaA.getText());
        double altura = Double.parseDouble(jTextMedidaAltura.getText());

        // Calcular el área del triángulo
        double area = calcularAreaTriangulo(ladoA, altura);

        // Mostrar el resultado en pantalla
        jLabelResultadoAreaTriangulo.setText("Área del triángulo: " + area);
    }

    private double calcularAreaTriangulo(double ladoA, double altura) {
        // Calcular el área del triángulo utilizando la fórmula: Área = (base * altura) / 2
        return (ladoA * altura) / 2;
    
    }//GEN-LAST:event_jButtonCalcularAreaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton jButtonCalcuLcularTipoTriangulo;
    javax.swing.JButton jButtonCalcularAngulos;
    javax.swing.JButton jButtonCalcularArea;
    javax.swing.JLabel jLabel1;
    javax.swing.JLabel jLabelResultadoAngulosTriangulo;
    javax.swing.JLabel jLabelResultadoAreaTriangulo;
    javax.swing.JLabel jLabelResultadoTipoTriangulo;
    javax.swing.JTextField jTextMedidaA;
    javax.swing.JTextField jTextMedidaAltura;
    javax.swing.JTextField jTextMedidaB;
    javax.swing.JTextField jTextMedidaC;
    // End of variables declaration//GEN-END:variables
}
